create table if not exists public.newsletter_metrics (
  id bigint generated by default as identity primary key,
  newsletter_id bigint not null references public.newsletters(id) on delete cascade,
  subscriber_id bigint not null references public.subscribers(id) on delete cascade,
  opened_at timestamptz,
  feedback text check (feedback in ('thumbs_up', 'thumbs_down'))
);
