create table if not exists public.sources (
  id bigint generated by default as identity primary key,
  team_id bigint references public.teams(id) on delete set null,
  url text not null unique,
  name text not null,
  type text not null check (type in ('general', 'team_specific', 'user_submitted')),
  status text not null check (status in ('pending', 'approved', 'rejected', 'flagged')),
  relevance_score integer,
  submitted_by text,
  created_at timestamptz not null default now(),
  paywall_rate numeric(5,2),
  beat_reporter boolean not null default false,
  is_wire_service boolean not null default false
);
