create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  city text not null,
  slug text not null unique,
  abbreviation text not null unique,
  primary_color text not null,
  secondary_color text not null,
  accent_color text not null,
  logo_url text,
  division text not null,
  conference text not null check (conference in ('AFC', 'NFC'))
);
