create table if not exists public.pipeline_runs (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete restrict,
  run_at timestamptz not null default now(),
  status text not null check (status in ('partial', 'completed', 'failed')) default 'partial',
  articles_fetched integer not null default 0,
  articles_passed_quality_gate integer not null default 0,
  articles_scored integer not null default 0,
  articles_selected integer not null default 0,
  notes text
);
