create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  team_id bigint not null references public.teams(id) on delete restrict,
  subscribed_at timestamptz not null default now(),
  is_active boolean not null default true,
  last_opened_at timestamptz
);
