create table if not exists public.newsletter_sends (
  id bigint generated by default as identity primary key,
  newsletter_id bigint not null references public.newsletters(id) on delete cascade,
  subscriber_id bigint not null references public.subscribers(id) on delete cascade,
  sent_at timestamptz not null default now(),
  status text not null check (status in ('sent', 'failed', 'bounced')),
  error_reason text
);
