create table if not exists public.newsletters (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete restrict,
  sent_at timestamptz,
  subject_line text not null,
  html_content text not null,
  status text not null check (status in ('draft', 'sent', 'failed')) default 'draft'
);
