create table if not exists public.engagement_snapshots (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete restrict,
  computed_at timestamptz not null default now(),
  period_start date not null,
  period_end date not null,
  active_subscribers integer not null default 0,
  day1_open_rate numeric(5,2),
  weekly_engagement_rate numeric(5,2),
  satisfaction_rate numeric(5,2),
  churned_count integer not null default 0
);
